server:
  port: 9001

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/D:/h2_database/database/msa-k8s;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    show-sql: false
  output:
    ansi:
      enabled: detect

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j